[package]
name = "hephaestus"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/hermes",]

[dependencies]
hermes = { path = "./crates/hermes"}

[[bin]]
name = "hephaestus"
path = "src/main.rs"
